In [4]:
import numpy as np

In [17]:
def sigmoid(x,deriv=False):
    if(deriv == True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [6]:
x = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1],[0,0,1]])
print(x.shape)

(5, 3)


In [7]:
y= np.array([[0],
             [1],
             [1],
             [0],
             [0]])
print(y.shape)

(5, 1)


In [8]:
np.random.seed(1)

In [12]:
w0 = 2*np.random.random((3,4)) - 1


In [13]:
w1 = 2*np.random.random((4,1))-1

In [14]:
print(w0,w1)

[[-0.1653904   0.11737966 -0.71922612 -0.60379702]
 [ 0.60148914  0.93652315 -0.37315164  0.38464523]
 [ 0.7527783   0.78921333 -0.82991158 -0.92189043]] [[-0.66033916]
 [ 0.75628501]
 [-0.80330633]
 [-0.15778475]]


In [18]:
for j in range(60000):
    l0 = x
    l1 = sigmoid(np.dot(l0,w0))
    l2 = sigmoid(np.dot(l1,w1))
    l2_error = y-l2
    if (j%10000) == 0:
        print ('Error'+str(np.mean(np.abs(l2_error))))
    l2_delta = l2_error * sigmoid(l2,deriv=True)
    l1_error = l2_delta.dot(w1.T)
    l1_delta = l1_error * sigmoid(l1,deriv=True)
    w1 += l1.T.dot(l2_delta)
    w0 += l0.T.dot(l1_delta)

Error0.4876744430011958
Error0.009042944552479152
Error0.006215892898693356
Error0.005012862860410831
Error0.004309076642966599
Error0.0038343434127862766
